name: chartlens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  csv: ^8.0.0
  diacritic: ^0.1.6
  flutter:
    sdk: flutter
  http: ^1.6.0
  path: ^1.9.1
  sqflite: ^2.4.3
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/hot100_2022_2025.json
    - assets/data/billboard200_2022_2025.csv